In [1]:
#Librerias a usar
import numpy as np
from scipy import linalg

In [5]:
#Declaro matriz - A(2X2)
A = np.array([[5,4],[3,7]])
A


array([[5, 4],
       [3, 7]])

In [6]:
#Calculo Inversa de la matriz
B = linalg.inv(A)
B

array([[ 0.30434783, -0.17391304],
       [-0.13043478,  0.2173913 ]])

In [7]:
#Compruebo el resultado con la matriz identidad

I = A.dot(B)
I

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
#Este es mi codigo
# Ismael Salazar